services:
  postgres:
    image: postgres:16-bookworm
    container_name: postgres-martenExample
    restart: always
    ports:
      - "6543:5432"  # localhost:6543 → container:5432 (standard Postgres port)
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - martenExample_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"  # pgAdmin UI → http://localhost:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json

volumes:
  martenExample_data:
